name: Rust

on:
  push:
    branches: [ "master", "copilot/fix-rust-workflow-errors" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  actions: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ gcc git curl wget nasm yasm cmake libgtk-3-dev clang libxcb-randr0-dev libxdo-dev libxfixes-dev libxcb-shape0-dev libxcb-xfixes0-dev libasound2-dev libpulse-dev libclang-dev libssl-dev libfuse-dev pkg-config libpam0g-dev
    - name: Cache
      uses: actions/cache@v5.0.1
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        # Just setup vcpkg, don't run install from manifest yet
        setupOnly: true
    - name: Install Dependencies
      shell: pwsh
      run: |
        $vcpkg = "$env:VCPKG_ROOT/vcpkg"
        & $vcpkg install libvpx libyuv opus aom --triplet x64-windows-static-md
    - name: Download Sciter
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.win/x64/sciter.dll" -OutFile "sciter.dll"
    - name: Build
      env:
        VCPKG_ROOT: ${{ env.RUNVCPKG_VCPKG_ROOT }}
      run: cargo build --release --verbose
    - name: Rename binary
      shell: powershell
      run: |
        cp target/release/rustdesk.exe target/release/rustdesk-hvnc.exe
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-windows-x64-release
        path: |
          target/release/rustdesk-hvnc.exe
          sciter.dll
